name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags: ["v*"]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/aiowx/${{ github.event.release.name }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - run: uv build

      - run: uv publish
